version: '3.8'

services:
  backend:
    image: dbmcristi/traffic-dashboard-be:4.0
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    image: dbmcristi/traffic-dashboard-ui-2.0
    container_name: frontend
    ports:
      - "3000:3000"
    #environment:
     # - REACT_APP_BACKEND_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
